apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: elasticsearch-second
  namespace: elastic-system
spec:
  version: 8.3.3
  nodeSets:
  - name: second
    count: 1 
    config:
      node.store.allow_mmap: false
    podTemplate:
      metadata:
        labels:
          scrape: es
---
apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: kibana-second
  namespace: elastic-system
spec:
  version: 8.3.3
  count: 1
  elasticsearchRef:
    name: elasticsearch-second
  podTemplate:
    metadata:
      labels:
       scrape: kb
